//
// Generated by build script (factory.pl)
//
#include "Factory.h"
#include <vector>

/* ----- generated code (start) ----- */


/* ----- generated code (end) ----- */

namespace etrobo
{

/**
 * ルールオブジェクトの一覧を作成する。
 * @return ルールオブジェクトの一覧
 */
std::vector<Rule*> Factory::createRuleObjects()
{
  std::vector<Rule*> list;

  /* ----- generated code (start) ----- */
  
  /* ----- generated code (end) ----- */

  return list;
}

/**
 * フィルタオブジェクトの一覧を作成する。
 * @return フィルタオブジェクトの一覧
 */
std::vector<Filter*> Factory::createFilterObjects()
{
  std::vector<Filter*> list;

  /* ----- generated code (start) ----- */
  
  /* ----- generated code (end) ----- */

  return list;
}

} // namespace etrobo
